### ISSUE TITLE
fail to compile ext_op

### ISSUE THREAD

**Issue by YJLCV** [zjjMaiMai/TinyHITNet#12]
Thank you for creating this great work! when I compile ext_op, error happened:more information（My cuda=11.0）：

Building wheels for collected packages: HitnetModule
  Building wheel for HitnetModule (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yjl/anaconda3/envs/hitnet/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-36lwpef7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-36lwpef7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n_dfk8lc
       cwd: /tmp/pip-req-build-36lwpef7/
  Complete output (87 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/HitnetModule
  copying src/HitnetModule/plane_fitting.py -> build/lib.linux-x86_64-3.8/HitnetModule
  copying src/HitnetModule/__init__.py -> build/lib.linux-x86_64-3.8/HitnetModule
  running build_ext
  building 'plane_fitting_c' extension
  creating /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8
  creating /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src
  creating /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting
  Emitting ninja build file /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/2] /home/yjl/local/cuda-10.0/bin/nvcc  -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/TH -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/THC -I/home/yjl/local/cuda-10.0/include -I/home/yjl/anaconda3/envs/hitnet/include/python3.8 -c -c /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting_cuda.cu -o /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=plane_fitting_c -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
  FAILED: /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting_cuda.o
  /home/yjl/local/cuda-10.0/bin/nvcc  -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/TH -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/THC -I/home/yjl/local/cuda-10.0/include -I/home/yjl/anaconda3/envs/hitnet/include/python3.8 -c -c /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting_cuda.cu -o /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=plane_fitting_c -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
  nvcc fatal   : Unsupported gpu architecture 'compute_80'
  [2/2] c++ -MMD -MF /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting.o.d -pthread -B /home/yjl/anaconda3/envs/hitnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/TH -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/THC -I/home/yjl/local/cuda-10.0/include -I/home/yjl/anaconda3/envs/hitnet/include/python3.8 -c -c /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting.cpp -o /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=plane_fitting_c -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                   from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                   from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                   from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                   from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                   from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                   from /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting.cpp:1:
  /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     87 | #pragma omp parallel for if ((end - begin) >= grain_size)
        |
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
      subprocess.run(
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-36lwpef7/setup.py", line 4, in <module>
      setup(
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
      build_ext.build_extensions(self)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
      _write_ninja_file_and_compile_objects(
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
      _run_ninja_build(
    File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for HitnetModule
  Running setup.py clean for HitnetModule
Failed to build HitnetModule
Installing collected packages: HitnetModule
    Running setup.py install for HitnetModule ... error
    ERROR: Command errored out with exit status 1:
     command: /home/yjl/anaconda3/envs/hitnet/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-36lwpef7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-36lwpef7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c2gnjtb9/install-record.txt --single-version-externally-managed --compile --install-headers /home/yjl/anaconda3/envs/hitnet/include/python3.8/HitnetModule
         cwd: /tmp/pip-req-build-36lwpef7/
    Complete output (89 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/HitnetModule
    copying src/HitnetModule/plane_fitting.py -> build/lib.linux-x86_64-3.8/HitnetModule
    copying src/HitnetModule/__init__.py -> build/lib.linux-x86_64-3.8/HitnetModule
    running build_ext
    building 'plane_fitting_c' extension
    creating /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8
    creating /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src
    creating /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting
    Emitting ninja build file /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] /home/yjl/local/cuda-10.0/bin/nvcc  -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/TH -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/THC -I/home/yjl/local/cuda-10.0/include -I/home/yjl/anaconda3/envs/hitnet/include/python3.8 -c -c /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting_cuda.cu -o /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=plane_fitting_c -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
    FAILED: /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting_cuda.o
    /home/yjl/local/cuda-10.0/bin/nvcc  -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/TH -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/THC -I/home/yjl/local/cuda-10.0/include -I/home/yjl/anaconda3/envs/hitnet/include/python3.8 -c -c /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting_cuda.cu -o /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=plane_fitting_c -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_80'
    [2/2] c++ -MMD -MF /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting.o.d -pthread -B /home/yjl/anaconda3/envs/hitnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/TH -I/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/THC -I/home/yjl/local/cuda-10.0/include -I/home/yjl/anaconda3/envs/hitnet/include/python3.8 -c -c /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting.cpp -o /tmp/pip-req-build-36lwpef7/build/temp.linux-x86_64-3.8/src/plane_fitting/plane_fitting.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=plane_fitting_c -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                     from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                     from /tmp/pip-req-build-36lwpef7/src/plane_fitting/plane_fitting.cpp:1:
    /home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
       87 | #pragma omp parallel for if ((end - begin) >= grain_size)
          |
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
        subprocess.run(
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-36lwpef7/setup.py", line 4, in <module>
        setup(
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/yjl/anaconda3/envs/hitnet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/yjl/anaconda3/envs/hitnet/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-36lwpef7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-36lwpef7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c2gnjtb9/install-record.txt --single-version-externally-managed --compile --install-headers /home/yjl/anaconda3/envs/hitnet/include/python3.8/HitnetModule Check the logs for full command output.

**Comment by zjjMaiMai** [comment]
> nvcc fatal : Unsupported gpu architecture 'compute_80'

see https://github.com/NVIDIA/cuda-samples/issues/44
